# Generated by Django 5.1.1 on 2025-11-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_seed_initial_patients"),
        ("profiles", "0003_patientprofile_role"),
    ]

    operations = []
