# Generated by Django 5.1.1 on 2025-11-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_merge_20251106_0915"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="onboarding_completed",
            field=models.BooleanField(
                default=False, help_text="Whether user has completed onboarding"
            ),
        ),
    ]
