# Generated by Django 5.0 on 2025-12-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_patientprofile_onboarding_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="address",
            field=models.TextField(
                blank=True, help_text="Patient's home address for finding nearby doctors"
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latitude of patient's location",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Longitude of patient's location",
                max_digits=9,
                null=True,
            ),
        ),
    ]
