# Generated by Django 5.1.1 on 2025-11-06 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TriageRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "symptom_description",
                    models.TextField(help_text="Patient's description of their symptoms"),
                ),
                (
                    "ai_severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mild", "Mild"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("emergency", "Emergency"),
                        ],
                        help_text="AI-assessed severity level",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "ai_summary",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated preliminary assessment summary",
                        null=True,
                    ),
                ),
                (
                    "ai_recommendations",
                    models.TextField(
                        blank=True, help_text="AI-generated recommendations", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triage_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Triage Request",
                "verbose_name_plural": "Triage Requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
