# Generated by Django 5.1.1 on 2025-11-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triage", "0002_triageinteraction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="triageinteraction",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AddField(
            model_name="triageinteraction",
            name="session_id",
            field=models.CharField(
                blank=True,
                help_text="Unique identifier for chat session",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="triageinteraction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="triageinteraction",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.DeleteModel(
            name="TriageRequest",
        ),
    ]
