# Generated by Django 5.1.1 on 2025-11-07 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triage", "0003_alter_triageinteraction_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="triageinteraction",
            name="assigned_doctor",
            field=models.ForeignKey(
                blank=True,
                help_text="Doctor/admin assigned to follow up on this triage report",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_triage_interactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="TriageDoctorNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("note", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        help_text="Doctor/admin who wrote the note",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triage_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "interaction",
                    models.ForeignKey(
                        help_text="Triage interaction this note belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="triage.triageinteraction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Triage Doctor Note",
                "verbose_name_plural": "Triage Doctor Notes",
                "ordering": ["-created_at"],
            },
        ),
    ]
