# Generated by Django 5.0 on 2025-11-07 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0003_alter_triageinteraction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='triageinteraction',
            name='doctor_notes',
            field=models.TextField(blank=True, help_text='Professional notes or feedback from doctor/admin', null=True),
        ),
        migrations.AddField(
            model_name='triageinteraction',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when doctor notes were last updated', null=True),
        ),
        migrations.AddField(
            model_name='triageinteraction',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Doctor/admin who reviewed this triage report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
