# Generated by Django 5.0 on 2025-11-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triage", "0006_merge_0004_migrations"),
    ]

    operations = [
        migrations.AddField(
            model_name="triageinteraction",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("pending_review", "Pending Review"),
                    ("under_review", "Under Review"),
                    ("finished_review", "Finished Review"),
                ],
                default="pending_review",
                help_text="Current status of the triage review process",
                max_length=20,
            ),
        ),
    ]
