# Generated by Django 5.1.1 on 2025-11-07 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("triage", "0004_triageinteraction_assigned_doctor_triagedoctornote"),
        ("triage", "0004_triageinteraction_doctor_notes_and_more"),
    ]

    operations = []
