# Generated by Django 6.0 on 2025-12-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("triage", "0007_triageinteraction_review_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="triageinteraction",
            name="data_integrity_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes regarding data integrity or discrepancies found",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="triageinteraction",
            name="data_integrity_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Verification"),
                    ("verified", "Verified - Consistent"),
                    ("discrepancy", "Discrepancy Found"),
                ],
                default="pending",
                help_text="Status of symptom verification against medical records",
                max_length=20,
            ),
        ),
    ]
