"""Management command to seed doctors across the United States."""

import time

from django.contrib.auth.models import User
from django.core.management.base import BaseCommand

from doctors.models import DoctorAvailability, DoctorProfile
from doctors.utils import geocode_location


class Command(BaseCommand):
    help = "Create doctors across major US cities with various specialties"

    def add_arguments(self, parser):
        parser.add_argument(
            "--count",
            type=int,
            default=20,
            help="Number of doctors to create (default: 20)",
        )

    def handle(self, *args, **options):
        # Doctors data with addresses across major US cities
        doctors_data = [
            # New York, NY
            {
                "username": "dr_ny_cardio",
                "first_name": "Michael",
                "last_name": "Chen",
                "email": "m.chen@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Manhattan Heart Center",
                "clinic_address": "130 E 77th St, New York, NY 10075",
                "consultation_fee": 300.00,
                "years_of_experience": 15,
            },
            {
                "username": "dr_ny_ped",
                "first_name": "Sarah",
                "last_name": "Rodriguez",
                "email": "s.rodriguez@carelink.com",
                "specialty": "Pediatrics",
                "clinic_name": "NYC Children's Hospital",
                "clinic_address": "525 E 68th St, New York, NY 10065",
                "consultation_fee": 200.00,
                "years_of_experience": 12,
            },
            # Los Angeles, CA
            {
                "username": "dr_la_derm",
                "first_name": "Jennifer",
                "last_name": "Kim",
                "email": "j.kim@carelink.com",
                "specialty": "Dermatology",
                "clinic_name": "Beverly Hills Dermatology",
                "clinic_address": "435 N Roxbury Dr, Beverly Hills, CA 90210",
                "consultation_fee": 350.00,
                "years_of_experience": 18,
            },
            {
                "username": "dr_la_ortho",
                "first_name": "David",
                "last_name": "Martinez",
                "email": "d.martinez@carelink.com",
                "specialty": "Orthopedics",
                "clinic_name": "LA Sports Medicine",
                "clinic_address": "200 Medical Plaza, Los Angeles, CA 90095",
                "consultation_fee": 400.00,
                "years_of_experience": 20,
            },
            # Chicago, IL
            {
                "username": "dr_chi_neuro",
                "first_name": "Robert",
                "last_name": "Johnson",
                "email": "r.johnson@carelink.com",
                "specialty": "Neurology",
                "clinic_name": "Chicago Neurological Institute",
                "clinic_address": "676 N St Clair St, Chicago, IL 60611",
                "consultation_fee": 350.00,
                "years_of_experience": 22,
            },
            {
                "username": "dr_chi_gp",
                "first_name": "Emily",
                "last_name": "White",
                "email": "e.white@carelink.com",
                "specialty": "General Practice",
                "clinic_name": "Chicago Family Medicine",
                "clinic_address": "150 E Huron St, Chicago, IL 60611",
                "consultation_fee": 150.00,
                "years_of_experience": 10,
            },
            # Houston, TX
            {
                "username": "dr_hou_obgyn",
                "first_name": "Maria",
                "last_name": "Garcia",
                "email": "m.garcia@carelink.com",
                "specialty": "Obstetrics & Gynecology",
                "clinic_name": "Houston Women's Health",
                "clinic_address": "6410 Fannin St, Houston, TX 77030",
                "consultation_fee": 250.00,
                "years_of_experience": 16,
            },
            {
                "username": "dr_hou_cardio",
                "first_name": "James",
                "last_name": "Wilson",
                "email": "j.wilson@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Texas Heart Institute",
                "clinic_address": "6770 Bertner Ave, Houston, TX 77030",
                "consultation_fee": 320.00,
                "years_of_experience": 19,
            },
            # Phoenix, AZ
            {
                "username": "dr_phx_psych",
                "first_name": "Patricia",
                "last_name": "Anderson",
                "email": "p.anderson.phx@carelink.com",
                "specialty": "Psychiatry",
                "clinic_name": "Phoenix Mental Health Center",
                "clinic_address": "1111 E McDowell Rd, Phoenix, AZ 85006",
                "consultation_fee": 280.00,
                "years_of_experience": 14,
            },
            # Philadelphia, PA
            {
                "username": "dr_phil_im",
                "first_name": "Thomas",
                "last_name": "Brown",
                "email": "t.brown@carelink.com",
                "specialty": "Internal Medicine",
                "clinic_name": "Penn Medicine",
                "clinic_address": "3400 Spruce St, Philadelphia, PA 19104",
                "consultation_fee": 220.00,
                "years_of_experience": 17,
            },
            # San Antonio, TX
            {
                "username": "dr_sa_ped",
                "first_name": "Lisa",
                "last_name": "Davis",
                "email": "l.davis@carelink.com",
                "specialty": "Pediatrics",
                "clinic_name": "San Antonio Children's Clinic",
                "clinic_address": "4502 Medical Dr, San Antonio, TX 78229",
                "consultation_fee": 180.00,
                "years_of_experience": 11,
            },
            # San Diego, CA
            {
                "username": "dr_sd_derm",
                "first_name": "Christopher",
                "last_name": "Lee",
                "email": "c.lee@carelink.com",
                "specialty": "Dermatology",
                "clinic_name": "San Diego Skin Care",
                "clinic_address": "200 W Arbor Dr, San Diego, CA 92103",
                "consultation_fee": 300.00,
                "years_of_experience": 13,
            },
            # Dallas, TX
            {
                "username": "dr_dal_ortho",
                "first_name": "Amanda",
                "last_name": "Taylor",
                "email": "a.taylor@carelink.com",
                "specialty": "Orthopedics",
                "clinic_name": "Dallas Orthopedic Center",
                "clinic_address": "5323 Harry Hines Blvd, Dallas, TX 75390",
                "consultation_fee": 380.00,
                "years_of_experience": 21,
            },
            # San Jose, CA
            {
                "username": "dr_sj_gp",
                "first_name": "Daniel",
                "last_name": "Nguyen",
                "email": "d.nguyen@carelink.com",
                "specialty": "General Practice",
                "clinic_name": "Silicon Valley Medical",
                "clinic_address": "250 Hospital Pkwy, San Jose, CA 95119",
                "consultation_fee": 160.00,
                "years_of_experience": 9,
            },
            # Austin, TX
            {
                "username": "dr_aus_cardio",
                "first_name": "Jessica",
                "last_name": "Moore",
                "email": "j.moore@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Austin Heart Center",
                "clinic_address": "1600 W 38th St, Austin, TX 78731",
                "consultation_fee": 310.00,
                "years_of_experience": 15,
            },
            # Jacksonville, FL
            {
                "username": "dr_jax_neuro",
                "first_name": "William",
                "last_name": "Jackson",
                "email": "w.jackson@carelink.com",
                "specialty": "Neurology",
                "clinic_name": "Jacksonville Neurological",
                "clinic_address": "800 Prudential Dr, Jacksonville, FL 32207",
                "consultation_fee": 340.00,
                "years_of_experience": 18,
            },
            # San Francisco, CA
            {
                "username": "dr_sf_psych",
                "first_name": "Michelle",
                "last_name": "Wong",
                "email": "m.wong@carelink.com",
                "specialty": "Psychiatry",
                "clinic_name": "SF Mental Health Services",
                "clinic_address": "505 Parnassus Ave, San Francisco, CA 94143",
                "consultation_fee": 320.00,
                "years_of_experience": 16,
            },
            # Columbus, OH
            {
                "username": "dr_col_obgyn",
                "first_name": "Nicole",
                "last_name": "Harris",
                "email": "n.harris@carelink.com",
                "specialty": "Obstetrics & Gynecology",
                "clinic_name": "Columbus Women's Health",
                "clinic_address": "410 W 10th Ave, Columbus, OH 43210",
                "consultation_fee": 240.00,
                "years_of_experience": 12,
            },
            # Fort Worth, TX
            {
                "username": "dr_fw_im",
                "first_name": "Kevin",
                "last_name": "Clark",
                "email": "k.clark@carelink.com",
                "specialty": "Internal Medicine",
                "clinic_name": "Fort Worth Medical Associates",
                "clinic_address": "1500 S Main St, Fort Worth, TX 76104",
                "consultation_fee": 190.00,
                "years_of_experience": 14,
            },
            # Charlotte, NC
            {
                "username": "dr_cha_ped",
                "first_name": "Rachel",
                "last_name": "Lewis",
                "email": "r.lewis@carelink.com",
                "specialty": "Pediatrics",
                "clinic_name": "Charlotte Children's Clinic",
                "clinic_address": "1000 Blythe Blvd, Charlotte, NC 28203",
                "consultation_fee": 170.00,
                "years_of_experience": 10,
            },
            # Seattle, WA
            {
                "username": "dr_sea_derm",
                "first_name": "Andrew",
                "last_name": "Young",
                "email": "a.young@carelink.com",
                "specialty": "Dermatology",
                "clinic_name": "Seattle Skin Specialists",
                "clinic_address": "325 9th Ave, Seattle, WA 98104",
                "consultation_fee": 290.00,
                "years_of_experience": 17,
            },
            # Denver, CO
            {
                "username": "dr_den_ortho",
                "first_name": "Stephanie",
                "last_name": "Hall",
                "email": "s.hall@carelink.com",
                "specialty": "Orthopedics",
                "clinic_name": "Denver Sports Medicine",
                "clinic_address": "12605 E 16th Ave, Aurora, CO 80045",
                "consultation_fee": 370.00,
                "years_of_experience": 19,
            },
            # Washington, DC
            {
                "username": "dr_dc_cardio",
                "first_name": "Brian",
                "last_name": "Allen",
                "email": "b.allen@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Washington Heart Institute",
                "clinic_address": "110 Irving St NW, Washington, DC 20010",
                "consultation_fee": 330.00,
                "years_of_experience": 20,
            },
            # Boston, MA
            {
                "username": "dr_bos_neuro",
                "first_name": "Lauren",
                "last_name": "King",
                "email": "l.king@carelink.com",
                "specialty": "Neurology",
                "clinic_name": "Boston Neurological Center",
                "clinic_address": "55 Fruit St, Boston, MA 02114",
                "consultation_fee": 360.00,
                "years_of_experience": 23,
            },
            # Miami, FL
            {
                "username": "dr_mia_psych",
                "first_name": "Carlos",
                "last_name": "Rivera",
                "email": "c.rivera@carelink.com",
                "specialty": "Psychiatry",
                "clinic_name": "Miami Mental Health",
                "clinic_address": "1611 NW 12th Ave, Miami, FL 33136",
                "consultation_fee": 270.00,
                "years_of_experience": 15,
            },
            # Portland, OR
            {
                "username": "dr_por_obgyn",
                "first_name": "Melissa",
                "last_name": "Wright",
                "email": "m.wright@carelink.com",
                "specialty": "Obstetrics & Gynecology",
                "clinic_name": "Portland Women's Health",
                "clinic_address": "3181 SW Sam Jackson Park Rd, Portland, OR 97239",
                "consultation_fee": 230.00,
                "years_of_experience": 13,
            },
            # Additional doctors in existing cities
            # New York, NY - More doctors
            {
                "username": "dr_ny_derm",
                "first_name": "Alexandra",
                "last_name": "Thompson",
                "email": "a.thompson@carelink.com",
                "specialty": "Dermatology",
                "clinic_name": "NYC Dermatology Center",
                "clinic_address": "1190 5th Ave, New York, NY 10029",
                "consultation_fee": 320.00,
                "years_of_experience": 14,
            },
            {
                "username": "dr_ny_ortho",
                "first_name": "Jonathan",
                "last_name": "Park",
                "email": "j.park@carelink.com",
                "specialty": "Orthopedics",
                "clinic_name": "Manhattan Orthopedic",
                "clinic_address": "535 E 70th St, New York, NY 10021",
                "consultation_fee": 380.00,
                "years_of_experience": 16,
            },
            {
                "username": "dr_ny_psych",
                "first_name": "Victoria",
                "last_name": "Chen",
                "email": "v.chen@carelink.com",
                "specialty": "Psychiatry",
                "clinic_name": "NYC Mental Health",
                "clinic_address": "622 W 168th St, New York, NY 10032",
                "consultation_fee": 280.00,
                "years_of_experience": 11,
            },
            {
                "username": "dr_ny_im",
                "first_name": "Richard",
                "last_name": "Adams",
                "email": "r.adams@carelink.com",
                "specialty": "Internal Medicine",
                "clinic_name": "Manhattan Internal Medicine",
                "clinic_address": "1 Gustave L Levy Pl, New York, NY 10029",
                "consultation_fee": 240.00,
                "years_of_experience": 13,
            },
            # Los Angeles, CA - More doctors
            {
                "username": "dr_la_cardio",
                "first_name": "Sofia",
                "last_name": "Lopez",
                "email": "s.lopez@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "LA Heart Center",
                "clinic_address": "8700 Beverly Blvd, Los Angeles, CA 90048",
                "consultation_fee": 340.00,
                "years_of_experience": 17,
            },
            {
                "username": "dr_la_ped",
                "first_name": "Ethan",
                "last_name": "Wong",
                "email": "e.wong@carelink.com",
                "specialty": "Pediatrics",
                "clinic_name": "LA Children's Medical",
                "clinic_address": "4650 Sunset Blvd, Los Angeles, CA 90027",
                "consultation_fee": 190.00,
                "years_of_experience": 9,
            },
            {
                "username": "dr_la_neuro",
                "first_name": "Olivia",
                "last_name": "Martinez",
                "email": "o.martinez@carelink.com",
                "specialty": "Neurology",
                "clinic_name": "LA Neurological Institute",
                "clinic_address": "757 Westwood Plaza, Los Angeles, CA 90095",
                "consultation_fee": 360.00,
                "years_of_experience": 19,
            },
            {
                "username": "dr_la_gp",
                "first_name": "Benjamin",
                "last_name": "Garcia",
                "email": "b.garcia@carelink.com",
                "specialty": "General Practice",
                "clinic_name": "LA Family Medicine",
                "clinic_address": "10833 Le Conte Ave, Los Angeles, CA 90095",
                "consultation_fee": 140.00,
                "years_of_experience": 8,
            },
            # Chicago, IL - More doctors
            {
                "username": "dr_chi_cardio",
                "first_name": "Madison",
                "last_name": "Scott",
                "email": "m.scott@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Chicago Heart Institute",
                "clinic_address": "251 E Huron St, Chicago, IL 60611",
                "consultation_fee": 330.00,
                "years_of_experience": 18,
            },
            {
                "username": "dr_chi_derm",
                "first_name": "Nathan",
                "last_name": "Green",
                "email": "n.green@carelink.com",
                "specialty": "Dermatology",
                "clinic_name": "Chicago Skin Care",
                "clinic_address": "675 N St Clair St, Chicago, IL 60611",
                "consultation_fee": 310.00,
                "years_of_experience": 15,
            },
            {
                "username": "dr_chi_obgyn",
                "first_name": "Isabella",
                "last_name": "Rivera",
                "email": "i.rivera@carelink.com",
                "specialty": "Obstetrics & Gynecology",
                "clinic_name": "Chicago Women's Health",
                "clinic_address": "259 E Erie St, Chicago, IL 60611",
                "consultation_fee": 260.00,
                "years_of_experience": 12,
            },
            # Houston, TX - More doctors
            {
                "username": "dr_hou_ortho",
                "first_name": "Daniel",
                "last_name": "Torres",
                "email": "d.torres@carelink.com",
                "specialty": "Orthopedics",
                "clinic_name": "Houston Orthopedic Center",
                "clinic_address": "6400 Fannin St, Houston, TX 77030",
                "consultation_fee": 390.00,
                "years_of_experience": 21,
            },
            {
                "username": "dr_hou_derm",
                "first_name": "Emma",
                "last_name": "Rodriguez",
                "email": "e.rodriguez@carelink.com",
                "specialty": "Dermatology",
                "clinic_name": "Houston Dermatology",
                "clinic_address": "6550 Fannin St, Houston, TX 77030",
                "consultation_fee": 290.00,
                "years_of_experience": 14,
            },
            {
                "username": "dr_hou_ped",
                "first_name": "Lucas",
                "last_name": "Sanchez",
                "email": "l.sanchez@carelink.com",
                "specialty": "Pediatrics",
                "clinic_name": "Houston Children's Clinic",
                "clinic_address": "6701 Fannin St, Houston, TX 77030",
                "consultation_fee": 175.00,
                "years_of_experience": 10,
            },
            # Phoenix, AZ - More doctors
            {
                "username": "dr_phx_cardio",
                "first_name": "Ava",
                "last_name": "Mitchell",
                "email": "a.mitchell@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Phoenix Heart Center",
                "clinic_address": "1441 N 12th St, Phoenix, AZ 85006",
                "consultation_fee": 315.00,
                "years_of_experience": 16,
            },
            {
                "username": "dr_phx_ortho",
                "first_name": "Mason",
                "last_name": "Perez",
                "email": "m.perez@carelink.com",
                "specialty": "Orthopedics",
                "clinic_name": "Phoenix Orthopedic",
                "clinic_address": "1300 N 12th St, Phoenix, AZ 85006",
                "consultation_fee": 365.00,
                "years_of_experience": 17,
            },
            # Philadelphia, PA - More doctors
            {
                "username": "dr_phil_cardio",
                "first_name": "Sophia",
                "last_name": "Roberts",
                "email": "s.roberts@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Philadelphia Heart Institute",
                "clinic_address": "3400 Spruce St, Philadelphia, PA 19104",
                "consultation_fee": 325.00,
                "years_of_experience": 19,
            },
            {
                "username": "dr_phil_ped",
                "first_name": "Logan",
                "last_name": "Turner",
                "email": "l.turner@carelink.com",
                "specialty": "Pediatrics",
                "clinic_name": "Philadelphia Children's Hospital",
                "clinic_address": "34th St & Civic Center Blvd, Philadelphia, PA 19104",
                "consultation_fee": 185.00,
                "years_of_experience": 11,
            },
            # San Antonio, TX - More doctors
            {
                "username": "dr_sa_cardio",
                "first_name": "Chloe",
                "last_name": "Phillips",
                "email": "c.phillips@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "San Antonio Heart Center",
                "clinic_address": "4502 Medical Dr, San Antonio, TX 78229",
                "consultation_fee": 305.00,
                "years_of_experience": 15,
            },
            {
                "username": "dr_sa_gp",
                "first_name": "Aiden",
                "last_name": "Campbell",
                "email": "a.campbell@carelink.com",
                "specialty": "General Practice",
                "clinic_name": "San Antonio Family Medicine",
                "clinic_address": "4410 Medical Dr, San Antonio, TX 78229",
                "consultation_fee": 135.00,
                "years_of_experience": 7,
            },
            # San Diego, CA - More doctors
            {
                "username": "dr_sd_cardio",
                "first_name": "Zoe",
                "last_name": "Parker",
                "email": "z.parker@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "San Diego Heart Institute",
                "clinic_address": "200 W Arbor Dr, San Diego, CA 92103",
                "consultation_fee": 318.00,
                "years_of_experience": 17,
            },
            {
                "username": "dr_sd_ped",
                "first_name": "Carter",
                "last_name": "Evans",
                "email": "c.evans@carelink.com",
                "specialty": "Pediatrics",
                "clinic_name": "San Diego Children's Hospital",
                "clinic_address": "3020 Children's Way, San Diego, CA 92123",
                "consultation_fee": 195.00,
                "years_of_experience": 12,
            },
            # Dallas, TX - More doctors
            {
                "username": "dr_dal_cardio",
                "first_name": "Lily",
                "last_name": "Edwards",
                "email": "l.edwards@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Dallas Heart Center",
                "clinic_address": "5323 Harry Hines Blvd, Dallas, TX 75390",
                "consultation_fee": 312.00,
                "years_of_experience": 18,
            },
            {
                "username": "dr_dal_derm",
                "first_name": "Wyatt",
                "last_name": "Collins",
                "email": "w.collins@carelink.com",
                "specialty": "Dermatology",
                "clinic_name": "Dallas Dermatology",
                "clinic_address": "1935 Medical District Dr, Dallas, TX 75235",
                "consultation_fee": 285.00,
                "years_of_experience": 13,
            },
            # San Jose, CA - More doctors
            {
                "username": "dr_sj_cardio",
                "first_name": "Natalie",
                "last_name": "Stewart",
                "email": "n.stewart@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Silicon Valley Heart Center",
                "clinic_address": "250 Hospital Pkwy, San Jose, CA 95119",
                "consultation_fee": 328.00,
                "years_of_experience": 20,
            },
            {
                "username": "dr_sj_ortho",
                "first_name": "Owen",
                "last_name": "Morris",
                "email": "o.morris@carelink.com",
                "specialty": "Orthopedics",
                "clinic_name": "San Jose Orthopedic",
                "clinic_address": "225 N Jackson Ave, San Jose, CA 95116",
                "consultation_fee": 375.00,
                "years_of_experience": 16,
            },
            # Austin, TX - More doctors
            {
                "username": "dr_aus_derm",
                "first_name": "Grace",
                "last_name": "Rogers",
                "email": "g.rogers@carelink.com",
                "specialty": "Dermatology",
                "clinic_name": "Austin Skin Care",
                "clinic_address": "1600 W 38th St, Austin, TX 78731",
                "consultation_fee": 295.00,
                "years_of_experience": 14,
            },
            {
                "username": "dr_aus_ped",
                "first_name": "Henry",
                "last_name": "Reed",
                "email": "h.reed@carelink.com",
                "specialty": "Pediatrics",
                "clinic_name": "Austin Children's Clinic",
                "clinic_address": "4900 Mueller Blvd, Austin, TX 78723",
                "consultation_fee": 180.00,
                "years_of_experience": 9,
            },
            # Jacksonville, FL - More doctors
            {
                "username": "dr_jax_cardio",
                "first_name": "Scarlett",
                "last_name": "Cook",
                "email": "s.cook@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Jacksonville Heart Center",
                "clinic_address": "800 Prudential Dr, Jacksonville, FL 32207",
                "consultation_fee": 308.00,
                "years_of_experience": 17,
            },
            {
                "username": "dr_jax_gp",
                "first_name": "Sebastian",
                "last_name": "Morgan",
                "email": "s.morgan@carelink.com",
                "specialty": "General Practice",
                "clinic_name": "Jacksonville Family Medicine",
                "clinic_address": "820 Prudential Dr, Jacksonville, FL 32207",
                "consultation_fee": 145.00,
                "years_of_experience": 8,
            },
            # San Francisco, CA - More doctors
            {
                "username": "dr_sf_cardio",
                "first_name": "Aria",
                "last_name": "Bell",
                "email": "a.bell@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "SF Heart Institute",
                "clinic_address": "505 Parnassus Ave, San Francisco, CA 94143",
                "consultation_fee": 335.00,
                "years_of_experience": 21,
            },
            {
                "username": "dr_sf_derm",
                "first_name": "Jack",
                "last_name": "Murphy",
                "email": "j.murphy@carelink.com",
                "specialty": "Dermatology",
                "clinic_name": "SF Dermatology Center",
                "clinic_address": "1701 Divisadero St, San Francisco, CA 94115",
                "consultation_fee": 305.00,
                "years_of_experience": 15,
            },
            # Columbus, OH - More doctors
            {
                "username": "dr_col_cardio",
                "first_name": "Luna",
                "last_name": "Bailey",
                "email": "l.bailey@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Columbus Heart Center",
                "clinic_address": "410 W 10th Ave, Columbus, OH 43210",
                "consultation_fee": 302.00,
                "years_of_experience": 16,
            },
            {
                "username": "dr_col_ped",
                "first_name": "Levi",
                "last_name": "Rivera",
                "email": "l.rivera.col@carelink.com",
                "specialty": "Pediatrics",
                "clinic_name": "Columbus Children's Hospital",
                "clinic_address": "700 Children's Dr, Columbus, OH 43205",
                "consultation_fee": 172.00,
                "years_of_experience": 10,
            },
            # Fort Worth, TX - More doctors
            {
                "username": "dr_fw_cardio",
                "first_name": "Hannah",
                "last_name": "Cooper",
                "email": "h.cooper@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Fort Worth Heart Center",
                "clinic_address": "1500 S Main St, Fort Worth, TX 76104",
                "consultation_fee": 300.00,
                "years_of_experience": 15,
            },
            {
                "username": "dr_fw_ortho",
                "first_name": "Maya",
                "last_name": "Richardson",
                "email": "m.richardson@carelink.com",
                "specialty": "Orthopedics",
                "clinic_name": "Fort Worth Orthopedic",
                "clinic_address": "1600 S Main St, Fort Worth, TX 76104",
                "consultation_fee": 360.00,
                "years_of_experience": 18,
            },
            # Charlotte, NC - More doctors
            {
                "username": "dr_cha_cardio",
                "first_name": "Ella",
                "last_name": "Cox",
                "email": "e.cox@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Charlotte Heart Institute",
                "clinic_address": "1000 Blythe Blvd, Charlotte, NC 28203",
                "consultation_fee": 298.00,
                "years_of_experience": 14,
            },
            {
                "username": "dr_cha_derm",
                "first_name": "Avery",
                "last_name": "Howard",
                "email": "a.howard@carelink.com",
                "specialty": "Dermatology",
                "clinic_name": "Charlotte Dermatology",
                "clinic_address": "1025 Morehead Medical Dr, Charlotte, NC 28204",
                "consultation_fee": 275.00,
                "years_of_experience": 12,
            },
            # Seattle, WA - More doctors
            {
                "username": "dr_sea_cardio",
                "first_name": "Addison",
                "last_name": "Ward",
                "email": "a.ward@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Seattle Heart Center",
                "clinic_address": "325 9th Ave, Seattle, WA 98104",
                "consultation_fee": 322.00,
                "years_of_experience": 19,
            },
            {
                "username": "dr_sea_ped",
                "first_name": "Eleanor",
                "last_name": "Torres",
                "email": "e.torres.sea@carelink.com",
                "specialty": "Pediatrics",
                "clinic_name": "Seattle Children's Hospital",
                "clinic_address": "4800 Sand Point Way NE, Seattle, WA 98105",
                "consultation_fee": 188.00,
                "years_of_experience": 11,
            },
            # Denver, CO - More doctors
            {
                "username": "dr_den_cardio",
                "first_name": "Stella",
                "last_name": "Peterson",
                "email": "s.peterson@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Denver Heart Institute",
                "clinic_address": "12605 E 16th Ave, Aurora, CO 80045",
                "consultation_fee": 315.00,
                "years_of_experience": 17,
            },
            {
                "username": "dr_den_derm",
                "first_name": "Penelope",
                "last_name": "Gray",
                "email": "p.gray@carelink.com",
                "specialty": "Dermatology",
                "clinic_name": "Denver Dermatology",
                "clinic_address": "1601 E 19th Ave, Denver, CO 80218",
                "consultation_fee": 280.00,
                "years_of_experience": 13,
            },
            # Washington, DC - More doctors
            {
                "username": "dr_dc_neuro",
                "first_name": "Hazel",
                "last_name": "Ramirez",
                "email": "h.ramirez@carelink.com",
                "specialty": "Neurology",
                "clinic_name": "DC Neurological Center",
                "clinic_address": "110 Irving St NW, Washington, DC 20010",
                "consultation_fee": 355.00,
                "years_of_experience": 20,
            },
            {
                "username": "dr_dc_ped",
                "first_name": "Violet",
                "last_name": "James",
                "email": "v.james@carelink.com",
                "specialty": "Pediatrics",
                "clinic_name": "DC Children's Hospital",
                "clinic_address": "111 Michigan Ave NW, Washington, DC 20010",
                "consultation_fee": 192.00,
                "years_of_experience": 10,
            },
            # Boston, MA - More doctors
            {
                "username": "dr_bos_cardio",
                "first_name": "Aurora",
                "last_name": "Watson",
                "email": "a.watson@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Boston Heart Institute",
                "clinic_address": "55 Fruit St, Boston, MA 02114",
                "consultation_fee": 340.00,
                "years_of_experience": 22,
            },
            {
                "username": "dr_bos_derm",
                "first_name": "Savannah",
                "last_name": "Brooks",
                "email": "s.brooks@carelink.com",
                "specialty": "Dermatology",
                "clinic_name": "Boston Dermatology",
                "clinic_address": "50 Staniford St, Boston, MA 02114",
                "consultation_fee": 310.00,
                "years_of_experience": 16,
            },
            # Miami, FL - More doctors
            {
                "username": "dr_mia_cardio",
                "first_name": "Audrey",
                "last_name": "Kelly",
                "email": "a.kelly@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Miami Heart Center",
                "clinic_address": "1611 NW 12th Ave, Miami, FL 33136",
                "consultation_fee": 318.00,
                "years_of_experience": 18,
            },
            {
                "username": "dr_mia_ortho",
                "first_name": "Brooklyn",
                "last_name": "Sanders",
                "email": "b.sanders@carelink.com",
                "specialty": "Orthopedics",
                "clinic_name": "Miami Orthopedic",
                "clinic_address": "1501 NW 10th Ave, Miami, FL 33136",
                "consultation_fee": 365.00,
                "years_of_experience": 19,
            },
            # Portland, OR - More doctors
            {
                "username": "dr_por_cardio",
                "first_name": "Bella",
                "last_name": "Price",
                "email": "b.price@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Portland Heart Center",
                "clinic_address": "3181 SW Sam Jackson Park Rd, Portland, OR 97239",
                "consultation_fee": 312.00,
                "years_of_experience": 16,
            },
            {
                "username": "dr_por_derm",
                "first_name": "Nora",
                "last_name": "Bennett",
                "email": "n.bennett@carelink.com",
                "specialty": "Dermatology",
                "clinic_name": "Portland Dermatology",
                "clinic_address": "3303 SW Bond Ave, Portland, OR 97239",
                "consultation_fee": 288.00,
                "years_of_experience": 14,
            },
            # Additional cities
            # Nashville, TN
            {
                "username": "dr_nash_cardio",
                "first_name": "Claire",
                "last_name": "Wood",
                "email": "c.wood@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Nashville Heart Center",
                "clinic_address": "1211 Medical Center Dr, Nashville, TN 37232",
                "consultation_fee": 295.00,
                "years_of_experience": 15,
            },
            {
                "username": "dr_nash_ped",
                "first_name": "Layla",
                "last_name": "Barnes",
                "email": "l.barnes@carelink.com",
                "specialty": "Pediatrics",
                "clinic_name": "Nashville Children's Hospital",
                "clinic_address": "2200 Children's Way, Nashville, TN 37232",
                "consultation_fee": 178.00,
                "years_of_experience": 9,
            },
            {
                "username": "dr_nash_gp",
                "first_name": "Zoe",
                "last_name": "Ross",
                "email": "z.ross.nash@carelink.com",
                "specialty": "General Practice",
                "clinic_name": "Nashville Family Medicine",
                "clinic_address": "110 29th Ave N, Nashville, TN 37203",
                "consultation_fee": 130.00,
                "years_of_experience": 6,
            },
            # Detroit, MI
            {
                "username": "dr_det_cardio",
                "first_name": "Lillian",
                "last_name": "Henderson",
                "email": "l.henderson@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Detroit Heart Institute",
                "clinic_address": "2799 W Grand Blvd, Detroit, MI 48202",
                "consultation_fee": 290.00,
                "years_of_experience": 14,
            },
            {
                "username": "dr_det_ortho",
                "first_name": "Aria",
                "last_name": "Coleman",
                "email": "a.coleman.det@carelink.com",
                "specialty": "Orthopedics",
                "clinic_name": "Detroit Orthopedic",
                "clinic_address": "18101 Oakwood Blvd, Dearborn, MI 48124",
                "consultation_fee": 350.00,
                "years_of_experience": 17,
            },
            # Memphis, TN
            {
                "username": "dr_mem_cardio",
                "first_name": "Natalie",
                "last_name": "Jenkins",
                "email": "n.jenkins@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Memphis Heart Center",
                "clinic_address": "1265 Union Ave, Memphis, TN 38104",
                "consultation_fee": 285.00,
                "years_of_experience": 13,
            },
            {
                "username": "dr_mem_ped",
                "first_name": "Leah",
                "last_name": "Perry",
                "email": "l.perry@carelink.com",
                "specialty": "Pediatrics",
                "clinic_name": "Memphis Children's Hospital",
                "clinic_address": "50 N Dunlap St, Memphis, TN 38103",
                "consultation_fee": 170.00,
                "years_of_experience": 8,
            },
            # Oklahoma City, OK
            {
                "username": "dr_okc_cardio",
                "first_name": "Hannah",
                "last_name": "Powell",
                "email": "h.powell@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Oklahoma Heart Center",
                "clinic_address": "1200 Everett Dr, Oklahoma City, OK 73104",
                "consultation_fee": 280.00,
                "years_of_experience": 12,
            },
            {
                "username": "dr_okc_gp",
                "first_name": "Mila",
                "last_name": "Long",
                "email": "m.long@carelink.com",
                "specialty": "General Practice",
                "clinic_name": "Oklahoma Family Medicine",
                "clinic_address": "800 NE 13th St, Oklahoma City, OK 73104",
                "consultation_fee": 125.00,
                "years_of_experience": 7,
            },
            # Las Vegas, NV
            {
                "username": "dr_lv_cardio",
                "first_name": "Aria",
                "last_name": "Patterson",
                "email": "a.patterson@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Las Vegas Heart Center",
                "clinic_address": "1800 W Charleston Blvd, Las Vegas, NV 89102",
                "consultation_fee": 300.00,
                "years_of_experience": 15,
            },
            {
                "username": "dr_lv_derm",
                "first_name": "Ellie",
                "last_name": "Hughes",
                "email": "e.hughes@carelink.com",
                "specialty": "Dermatology",
                "clinic_name": "Las Vegas Dermatology",
                "clinic_address": "1701 W Charleston Blvd, Las Vegas, NV 89102",
                "consultation_fee": 275.00,
                "years_of_experience": 13,
            },
            # Louisville, KY
            {
                "username": "dr_lou_cardio",
                "first_name": "Aaliyah",
                "last_name": "Flores",
                "email": "a.flores@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Louisville Heart Center",
                "clinic_address": "530 S Jackson St, Louisville, KY 40202",
                "consultation_fee": 288.00,
                "years_of_experience": 14,
            },
            {
                "username": "dr_lou_ped",
                "first_name": "Nova",
                "last_name": "Washington",
                "email": "n.washington@carelink.com",
                "specialty": "Pediatrics",
                "clinic_name": "Louisville Children's Hospital",
                "clinic_address": "231 E Chestnut St, Louisville, KY 40202",
                "consultation_fee": 165.00,
                "years_of_experience": 9,
            },
            # Baltimore, MD
            {
                "username": "dr_bal_cardio",
                "first_name": "Willow",
                "last_name": "Butler",
                "email": "w.butler@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Baltimore Heart Institute",
                "clinic_address": "600 N Wolfe St, Baltimore, MD 21287",
                "consultation_fee": 310.00,
                "years_of_experience": 18,
            },
            {
                "username": "dr_bal_ortho",
                "first_name": "Quinn",
                "last_name": "Simmons",
                "email": "q.simmons@carelink.com",
                "specialty": "Orthopedics",
                "clinic_name": "Baltimore Orthopedic",
                "clinic_address": "601 N Caroline St, Baltimore, MD 21287",
                "consultation_fee": 355.00,
                "years_of_experience": 19,
            },
            # Milwaukee, WI
            {
                "username": "dr_mil_cardio",
                "first_name": "Ivy",
                "last_name": "Foster",
                "email": "i.foster@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Milwaukee Heart Center",
                "clinic_address": "9200 W Wisconsin Ave, Milwaukee, WI 53226",
                "consultation_fee": 292.00,
                "years_of_experience": 15,
            },
            {
                "username": "dr_mil_ped",
                "first_name": "Paisley",
                "last_name": "Gonzales",
                "email": "p.gonzales@carelink.com",
                "specialty": "Pediatrics",
                "clinic_name": "Milwaukee Children's Hospital",
                "clinic_address": "9000 W Wisconsin Ave, Milwaukee, WI 53226",
                "consultation_fee": 173.00,
                "years_of_experience": 10,
            },
            # Albuquerque, NM
            {
                "username": "dr_alb_cardio",
                "first_name": "Delilah",
                "last_name": "Bryant",
                "email": "d.bryant@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Albuquerque Heart Center",
                "clinic_address": "2211 Lomas Blvd NE, Albuquerque, NM 87106",
                "consultation_fee": 278.00,
                "years_of_experience": 13,
            },
            {
                "username": "dr_alb_gp",
                "first_name": "Serenity",
                "last_name": "Alexander",
                "email": "s.alexander@carelink.com",
                "specialty": "General Practice",
                "clinic_name": "Albuquerque Family Medicine",
                "clinic_address": "1201 Camino de Salud NE, Albuquerque, NM 87102",
                "consultation_fee": 128.00,
                "years_of_experience": 8,
            },
            # Tucson, AZ
            {
                "username": "dr_tuc_cardio",
                "first_name": "Ariana",
                "last_name": "Russell",
                "email": "a.russell@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Tucson Heart Center",
                "clinic_address": "1501 N Campbell Ave, Tucson, AZ 85724",
                "consultation_fee": 275.00,
                "years_of_experience": 12,
            },
            {
                "username": "dr_tuc_derm",
                "first_name": "Kinsley",
                "last_name": "Griffin",
                "email": "k.griffin@carelink.com",
                "specialty": "Dermatology",
                "clinic_name": "Tucson Dermatology",
                "clinic_address": "1601 N Tucson Blvd, Tucson, AZ 85716",
                "consultation_fee": 265.00,
                "years_of_experience": 11,
            },
            # Fresno, CA
            {
                "username": "dr_fre_cardio",
                "first_name": "Allison",
                "last_name": "Diaz",
                "email": "a.diaz@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Fresno Heart Center",
                "clinic_address": "2823 Fresno St, Fresno, CA 93721",
                "consultation_fee": 272.00,
                "years_of_experience": 11,
            },
            {
                "username": "dr_fre_ped",
                "first_name": "Anna",
                "last_name": "Hayes",
                "email": "a.hayes@carelink.com",
                "specialty": "Pediatrics",
                "clinic_name": "Fresno Children's Hospital",
                "clinic_address": "9300 Valley Children's Pl, Madera, CA 93636",
                "consultation_fee": 168.00,
                "years_of_experience": 8,
            },
            # Sacramento, CA
            {
                "username": "dr_sac_cardio",
                "first_name": "Caroline",
                "last_name": "Myers",
                "email": "c.myers@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Sacramento Heart Center",
                "clinic_address": "2315 Stockton Blvd, Sacramento, CA 95817",
                "consultation_fee": 285.00,
                "years_of_experience": 14,
            },
            {
                "username": "dr_sac_ortho",
                "first_name": "Genesis",
                "last_name": "Ford",
                "email": "g.ford@carelink.com",
                "specialty": "Orthopedics",
                "clinic_name": "Sacramento Orthopedic",
                "clinic_address": "4860 Y St, Sacramento, CA 95817",
                "consultation_fee": 342.00,
                "years_of_experience": 16,
            },
            # Kansas City, MO
            {
                "username": "dr_kc_cardio",
                "first_name": "Aubrey",
                "last_name": "Hamilton",
                "email": "a.hamilton@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Kansas City Heart Center",
                "clinic_address": "2301 Holmes St, Kansas City, MO 64108",
                "consultation_fee": 282.00,
                "years_of_experience": 13,
            },
            {
                "username": "dr_kc_ped",
                "first_name": "Brianna",
                "last_name": "Graham",
                "email": "b.graham@carelink.com",
                "specialty": "Pediatrics",
                "clinic_name": "Kansas City Children's Hospital",
                "clinic_address": "2401 Gillham Rd, Kansas City, MO 64108",
                "consultation_fee": 166.00,
                "years_of_experience": 9,
            },
            # Mesa, AZ
            {
                "username": "dr_mes_cardio",
                "first_name": "Skylar",
                "last_name": "Sullivan",
                "email": "s.sullivan@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Mesa Heart Center",
                "clinic_address": "1400 S Dobson Rd, Mesa, AZ 85202",
                "consultation_fee": 270.00,
                "years_of_experience": 12,
            },
            {
                "username": "dr_mes_gp",
                "first_name": "Lucy",
                "last_name": "Wallace",
                "email": "l.wallace@carelink.com",
                "specialty": "General Practice",
                "clinic_name": "Mesa Family Medicine",
                "clinic_address": "1012 E Baseline Rd, Mesa, AZ 85204",
                "consultation_fee": 122.00,
                "years_of_experience": 7,
            },
            # Virginia Beach, VA
            {
                "username": "dr_vb_cardio",
                "first_name": "Aria",
                "last_name": "Woods",
                "email": "a.woods.vb@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Virginia Beach Heart Center",
                "clinic_address": "600 Gresham Dr, Norfolk, VA 23507",
                "consultation_fee": 288.00,
                "years_of_experience": 14,
            },
            {
                "username": "dr_vb_ped",
                "first_name": "Eleanor",
                "last_name": "Cole",
                "email": "e.cole.vb@carelink.com",
                "specialty": "Pediatrics",
                "clinic_name": "Virginia Beach Children's Hospital",
                "clinic_address": "601 Children's Ln, Norfolk, VA 23507",
                "consultation_fee": 171.00,
                "years_of_experience": 10,
            },
            # Oakland, CA
            {
                "username": "dr_oak_cardio",
                "first_name": "Madeline",
                "last_name": "West",
                "email": "m.west@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Oakland Heart Center",
                "clinic_address": "747 52nd St, Oakland, CA 94609",
                "consultation_fee": 305.00,
                "years_of_experience": 16,
            },
            {
                "username": "dr_oak_derm",
                "first_name": "Cora",
                "last_name": "Jordan",
                "email": "c.jordan@carelink.com",
                "specialty": "Dermatology",
                "clinic_name": "Oakland Dermatology",
                "clinic_address": "350 30th St, Oakland, CA 94609",
                "consultation_fee": 278.00,
                "years_of_experience": 13,
            },
            # Minneapolis, MN
            {
                "username": "dr_min_cardio",
                "first_name": "Ruby",
                "last_name": "Owens",
                "email": "r.owens@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Minneapolis Heart Institute",
                "clinic_address": "800 E 28th St, Minneapolis, MN 55407",
                "consultation_fee": 295.00,
                "years_of_experience": 15,
            },
            {
                "username": "dr_min_ped",
                "first_name": "Eva",
                "last_name": "Reyes",
                "email": "e.reyes@carelink.com",
                "specialty": "Pediatrics",
                "clinic_name": "Minneapolis Children's Hospital",
                "clinic_address": "2525 Chicago Ave, Minneapolis, MN 55404",
                "consultation_fee": 177.00,
                "years_of_experience": 9,
            },
            # Tulsa, OK
            {
                "username": "dr_tul_cardio",
                "first_name": "Clara",
                "last_name": "Kim",
                "email": "c.kim.tul@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Tulsa Heart Center",
                "clinic_address": "6161 S Yale Ave, Tulsa, OK 74136",
                "consultation_fee": 275.00,
                "years_of_experience": 13,
            },
            {
                "username": "dr_tul_gp",
                "first_name": "Vivian",
                "last_name": "Castillo",
                "email": "v.castillo@carelink.com",
                "specialty": "General Practice",
                "clinic_name": "Tulsa Family Medicine",
                "clinic_address": "1145 S Utica Ave, Tulsa, OK 74104",
                "consultation_fee": 120.00,
                "years_of_experience": 6,
            },
            # Arlington, TX
            {
                "username": "dr_arl_cardio",
                "first_name": "Stella",
                "last_name": "Wheeler",
                "email": "s.wheeler@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Arlington Heart Center",
                "clinic_address": "800 W Randol Mill Rd, Arlington, TX 76012",
                "consultation_fee": 278.00,
                "years_of_experience": 12,
            },
            {
                "username": "dr_arl_ped",
                "first_name": "Hazel",
                "last_name": "Chapman",
                "email": "h.chapman@carelink.com",
                "specialty": "Pediatrics",
                "clinic_name": "Arlington Children's Clinic",
                "clinic_address": "801 W Randol Mill Rd, Arlington, TX 76012",
                "consultation_fee": 164.00,
                "years_of_experience": 8,
            },
            # Tampa, FL
            {
                "username": "dr_tam_cardio",
                "first_name": "Luna",
                "last_name": "Oliver",
                "email": "l.oliver@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Tampa Heart Institute",
                "clinic_address": "1 Tampa General Cir, Tampa, FL 33606",
                "consultation_fee": 300.00,
                "years_of_experience": 16,
            },
            {
                "username": "dr_tam_derm",
                "first_name": "Aurora",
                "last_name": "George",
                "email": "a.george.tam@carelink.com",
                "specialty": "Dermatology",
                "clinic_name": "Tampa Dermatology",
                "clinic_address": "2 Tampa General Cir, Tampa, FL 33606",
                "consultation_fee": 272.00,
                "years_of_experience": 14,
            },
            # New Orleans, LA
            {
                "username": "dr_no_cardio",
                "first_name": "Nova",
                "last_name": "Lopez",
                "email": "n.lopez.no@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "New Orleans Heart Center",
                "clinic_address": "1514 Jefferson Hwy, New Orleans, LA 70121",
                "consultation_fee": 285.00,
                "years_of_experience": 14,
            },
            {
                "username": "dr_no_ped",
                "first_name": "Willow",
                "last_name": "Ferguson",
                "email": "w.ferguson@carelink.com",
                "specialty": "Pediatrics",
                "clinic_name": "New Orleans Children's Hospital",
                "clinic_address": "200 Henry Clay Ave, New Orleans, LA 70118",
                "consultation_fee": 169.00,
                "years_of_experience": 9,
            },
            # Cleveland, OH
            {
                "username": "dr_cle_cardio",
                "first_name": "Ivy",
                "last_name": "Garza",
                "email": "i.garza@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Cleveland Heart Institute",
                "clinic_address": "9500 Euclid Ave, Cleveland, OH 44195",
                "consultation_fee": 310.00,
                "years_of_experience": 17,
            },
            {
                "username": "dr_cle_ortho",
                "first_name": "Paisley",
                "last_name": "Lawson",
                "email": "p.lawson@carelink.com",
                "specialty": "Orthopedics",
                "clinic_name": "Cleveland Orthopedic",
                "clinic_address": "9500 Euclid Ave, Cleveland, OH 44195",
                "consultation_fee": 348.00,
                "years_of_experience": 18,
            },
            # Wichita, KS
            {
                "username": "dr_wic_cardio",
                "first_name": "Delilah",
                "last_name": "Fields",
                "email": "d.fields@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Wichita Heart Center",
                "clinic_address": "929 N Waco St, Wichita, KS 67203",
                "consultation_fee": 268.00,
                "years_of_experience": 11,
            },
            {
                "username": "dr_wic_gp",
                "first_name": "Serenity",
                "last_name": "Gutierrez",
                "email": "s.gutierrez@carelink.com",
                "specialty": "General Practice",
                "clinic_name": "Wichita Family Medicine",
                "clinic_address": "1120 N Topeka St, Wichita, KS 67214",
                "consultation_fee": 118.00,
                "years_of_experience": 5,
            },
            # Bakersfield, CA
            {
                "username": "dr_bak_cardio",
                "first_name": "Ariana",
                "last_name": "Schmidt",
                "email": "a.schmidt@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Bakersfield Heart Center",
                "clinic_address": "1830 Flower St, Bakersfield, CA 93305",
                "consultation_fee": 265.00,
                "years_of_experience": 10,
            },
            {
                "username": "dr_bak_ped",
                "first_name": "Kinsley",
                "last_name": "Carr",
                "email": "k.carr@carelink.com",
                "specialty": "Pediatrics",
                "clinic_name": "Bakersfield Children's Clinic",
                "clinic_address": "1700 Mount Vernon Ave, Bakersfield, CA 93306",
                "consultation_fee": 162.00,
                "years_of_experience": 7,
            },
            # Aurora, CO - More doctors
            {
                "username": "dr_aur_cardio",
                "first_name": "Allison",
                "last_name": "Vargas",
                "email": "a.vargas@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Aurora Heart Center",
                "clinic_address": "12605 E 16th Ave, Aurora, CO 80045",
                "consultation_fee": 302.00,
                "years_of_experience": 15,
            },
            {
                "username": "dr_aur_ped",
                "first_name": "Anna",
                "last_name": "Ramos",
                "email": "a.ramos@carelink.com",
                "specialty": "Pediatrics",
                "clinic_name": "Aurora Children's Hospital",
                "clinic_address": "13123 E 16th Ave, Aurora, CO 80045",
                "consultation_fee": 174.00,
                "years_of_experience": 9,
            },
            # Raleigh, NC
            {
                "username": "dr_ral_cardio",
                "first_name": "Caroline",
                "last_name": "Francis",
                "email": "c.francis@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Raleigh Heart Center",
                "clinic_address": "3000 New Bern Ave, Raleigh, NC 27610",
                "consultation_fee": 292.00,
                "years_of_experience": 14,
            },
            {
                "username": "dr_ral_derm",
                "first_name": "Genesis",
                "last_name": "Shaw",
                "email": "g.shaw@carelink.com",
                "specialty": "Dermatology",
                "clinic_name": "Raleigh Dermatology",
                "clinic_address": "3100 Blue Ridge Rd, Raleigh, NC 27612",
                "consultation_fee": 268.00,
                "years_of_experience": 12,
            },
            # Omaha, NE
            {
                "username": "dr_oma_cardio",
                "first_name": "Aubrey",
                "last_name": "Gibson",
                "email": "a.gibson@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Omaha Heart Center",
                "clinic_address": "8200 Dodge St, Omaha, NE 68114",
                "consultation_fee": 275.00,
                "years_of_experience": 13,
            },
            {
                "username": "dr_oma_ped",
                "first_name": "Brianna",
                "last_name": "Snyder",
                "email": "b.snyder@carelink.com",
                "specialty": "Pediatrics",
                "clinic_name": "Omaha Children's Hospital",
                "clinic_address": "8200 Dodge St, Omaha, NE 68114",
                "consultation_fee": 167.00,
                "years_of_experience": 8,
            },
            # Miami, FL - More doctors
            {
                "username": "dr_mia_derm",
                "first_name": "Skylar",
                "last_name": "Hart",
                "email": "s.hart@carelink.com",
                "specialty": "Dermatology",
                "clinic_name": "Miami Dermatology",
                "clinic_address": "1611 NW 12th Ave, Miami, FL 33136",
                "consultation_fee": 282.00,
                "years_of_experience": 13,
            },
            {
                "username": "dr_mia_ped",
                "first_name": "Lucy",
                "last_name": "Bradley",
                "email": "l.bradley@carelink.com",
                "specialty": "Pediatrics",
                "clinic_name": "Miami Children's Hospital",
                "clinic_address": "3100 SW 62nd Ave, Miami, FL 33155",
                "consultation_fee": 186.00,
                "years_of_experience": 10,
            },
            # Long Beach, CA
            {
                "username": "dr_lb_cardio",
                "first_name": "Aria",
                "last_name": "Lane",
                "email": "a.lane@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Long Beach Heart Center",
                "clinic_address": "2801 Atlantic Ave, Long Beach, CA 90806",
                "consultation_fee": 298.00,
                "years_of_experience": 15,
            },
            {
                "username": "dr_lb_ortho",
                "first_name": "Eleanor",
                "last_name": "Andrews",
                "email": "e.andrews@carelink.com",
                "specialty": "Orthopedics",
                "clinic_name": "Long Beach Orthopedic",
                "clinic_address": "2801 Atlantic Ave, Long Beach, CA 90806",
                "consultation_fee": 352.00,
                "years_of_experience": 17,
            },
            # Virginia Beach, VA - More doctors
            {
                "username": "dr_vb_ortho",
                "first_name": "Madeline",
                "last_name": "Ruiz",
                "email": "m.ruiz@carelink.com",
                "specialty": "Orthopedics",
                "clinic_name": "Virginia Beach Orthopedic",
                "clinic_address": "600 Gresham Dr, Norfolk, VA 23507",
                "consultation_fee": 345.00,
                "years_of_experience": 18,
            },
            {
                "username": "dr_vb_gp",
                "first_name": "Cora",
                "last_name": "Harper",
                "email": "c.harper@carelink.com",
                "specialty": "General Practice",
                "clinic_name": "Virginia Beach Family Medicine",
                "clinic_address": "601 Children's Ln, Norfolk, VA 23507",
                "consultation_fee": 138.00,
                "years_of_experience": 7,
            },
            # Oakland, CA - More doctors
            {
                "username": "dr_oak_ped",
                "first_name": "Ruby",
                "last_name": "Fox",
                "email": "r.fox@carelink.com",
                "specialty": "Pediatrics",
                "clinic_name": "Oakland Children's Hospital",
                "clinic_address": "747 52nd St, Oakland, CA 94609",
                "consultation_fee": 190.00,
                "years_of_experience": 11,
            },
            {
                "username": "dr_oak_im",
                "first_name": "Eva",
                "last_name": "Riley",
                "email": "e.riley@carelink.com",
                "specialty": "Internal Medicine",
                "clinic_name": "Oakland Internal Medicine",
                "clinic_address": "350 30th St, Oakland, CA 94609",
                "consultation_fee": 210.00,
                "years_of_experience": 12,
            },
            # Minneapolis, MN - More doctors
            {
                "username": "dr_min_derm",
                "first_name": "Clara",
                "last_name": "Carpenter",
                "email": "c.carpenter@carelink.com",
                "specialty": "Dermatology",
                "clinic_name": "Minneapolis Dermatology",
                "clinic_address": "800 E 28th St, Minneapolis, MN 55407",
                "consultation_fee": 273.00,
                "years_of_experience": 12,
            },
            {
                "username": "dr_min_gp",
                "first_name": "Vivian",
                "last_name": "Weaver",
                "email": "v.weaver@carelink.com",
                "specialty": "General Practice",
                "clinic_name": "Minneapolis Family Medicine",
                "clinic_address": "2525 Chicago Ave, Minneapolis, MN 55404",
                "consultation_fee": 142.00,
                "years_of_experience": 8,
            },
            # Tulsa, OK - More doctors
            {
                "username": "dr_tul_ortho",
                "first_name": "Stella",
                "last_name": "Daniels",
                "email": "s.daniels@carelink.com",
                "specialty": "Orthopedics",
                "clinic_name": "Tulsa Orthopedic",
                "clinic_address": "6161 S Yale Ave, Tulsa, OK 74136",
                "consultation_fee": 338.00,
                "years_of_experience": 16,
            },
            {
                "username": "dr_tul_ped",
                "first_name": "Hazel",
                "last_name": "Stephens",
                "email": "h.stephens@carelink.com",
                "specialty": "Pediatrics",
                "clinic_name": "Tulsa Children's Hospital",
                "clinic_address": "1145 S Utica Ave, Tulsa, OK 74104",
                "consultation_fee": 163.00,
                "years_of_experience": 7,
            },
            # Arlington, TX - More doctors
            {
                "username": "dr_arl_derm",
                "first_name": "Luna",
                "last_name": "Mendoza",
                "email": "l.mendoza@carelink.com",
                "specialty": "Dermatology",
                "clinic_name": "Arlington Dermatology",
                "clinic_address": "800 W Randol Mill Rd, Arlington, TX 76012",
                "consultation_fee": 270.00,
                "years_of_experience": 11,
            },
            {
                "username": "dr_arl_gp",
                "first_name": "Aurora",
                "last_name": "Curtis",
                "email": "a.curtis@carelink.com",
                "specialty": "General Practice",
                "clinic_name": "Arlington Family Medicine",
                "clinic_address": "801 W Randol Mill Rd, Arlington, TX 76012",
                "consultation_fee": 132.00,
                "years_of_experience": 6,
            },
            # Tampa, FL - More doctors
            {
                "username": "dr_tam_ortho",
                "first_name": "Nova",
                "last_name": "Pearce",
                "email": "n.pearce@carelink.com",
                "specialty": "Orthopedics",
                "clinic_name": "Tampa Orthopedic",
                "clinic_address": "1 Tampa General Cir, Tampa, FL 33606",
                "consultation_fee": 348.00,
                "years_of_experience": 17,
            },
            {
                "username": "dr_tam_ped",
                "first_name": "Willow",
                "last_name": "Dean",
                "email": "w.dean@carelink.com",
                "specialty": "Pediatrics",
                "clinic_name": "Tampa Children's Hospital",
                "clinic_address": "2 Tampa General Cir, Tampa, FL 33606",
                "consultation_fee": 185.00,
                "years_of_experience": 9,
            },
            # New Orleans, LA - More doctors
            {
                "username": "dr_no_derm",
                "first_name": "Ivy",
                "last_name": "Barker",
                "email": "i.barker@carelink.com",
                "specialty": "Dermatology",
                "clinic_name": "New Orleans Dermatology",
                "clinic_address": "1514 Jefferson Hwy, New Orleans, LA 70121",
                "consultation_fee": 268.00,
                "years_of_experience": 12,
            },
            {
                "username": "dr_no_gp",
                "first_name": "Paisley",
                "last_name": "Horton",
                "email": "p.horton@carelink.com",
                "specialty": "General Practice",
                "clinic_name": "New Orleans Family Medicine",
                "clinic_address": "200 Henry Clay Ave, New Orleans, LA 70118",
                "consultation_fee": 136.00,
                "years_of_experience": 7,
            },
            # Cleveland, OH - More doctors
            {
                "username": "dr_cle_derm",
                "first_name": "Delilah",
                "last_name": "Terry",
                "email": "d.terry@carelink.com",
                "specialty": "Dermatology",
                "clinic_name": "Cleveland Dermatology",
                "clinic_address": "9500 Euclid Ave, Cleveland, OH 44195",
                "consultation_fee": 288.00,
                "years_of_experience": 13,
            },
            {
                "username": "dr_cle_ped",
                "first_name": "Serenity",
                "last_name": "Welch",
                "email": "s.welch@carelink.com",
                "specialty": "Pediatrics",
                "clinic_name": "Cleveland Children's Hospital",
                "clinic_address": "11100 Euclid Ave, Cleveland, OH 44106",
                "consultation_fee": 179.00,
                "years_of_experience": 10,
            },
            # Wichita, KS - More doctors
            {
                "username": "dr_wic_ortho",
                "first_name": "Ariana",
                "last_name": "Baldwin",
                "email": "a.baldwin@carelink.com",
                "specialty": "Orthopedics",
                "clinic_name": "Wichita Orthopedic",
                "clinic_address": "929 N Waco St, Wichita, KS 67203",
                "consultation_fee": 325.00,
                "years_of_experience": 15,
            },
            {
                "username": "dr_wic_ped",
                "first_name": "Kinsley",
                "last_name": "Ortega",
                "email": "k.ortega@carelink.com",
                "specialty": "Pediatrics",
                "clinic_name": "Wichita Children's Hospital",
                "clinic_address": "1120 N Topeka St, Wichita, KS 67214",
                "consultation_fee": 161.00,
                "years_of_experience": 8,
            },
            # Bakersfield, CA - More doctors
            {
                "username": "dr_bak_derm",
                "first_name": "Allison",
                "last_name": "Dennis",
                "email": "a.dennis@carelink.com",
                "specialty": "Dermatology",
                "clinic_name": "Bakersfield Dermatology",
                "clinic_address": "1830 Flower St, Bakersfield, CA 93305",
                "consultation_fee": 258.00,
                "years_of_experience": 10,
            },
            {
                "username": "dr_bak_gp",
                "first_name": "Anna",
                "last_name": "McClure",
                "email": "a.mcclure@carelink.com",
                "specialty": "General Practice",
                "clinic_name": "Bakersfield Family Medicine",
                "clinic_address": "1700 Mount Vernon Ave, Bakersfield, CA 93306",
                "consultation_fee": 124.00,
                "years_of_experience": 6,
            },
            # Aurora, CO - More doctors
            {
                "username": "dr_aur_derm",
                "first_name": "Caroline",
                "last_name": "Blackburn",
                "email": "c.blackburn@carelink.com",
                "specialty": "Dermatology",
                "clinic_name": "Aurora Dermatology",
                "clinic_address": "12605 E 16th Ave, Aurora, CO 80045",
                "consultation_fee": 275.00,
                "years_of_experience": 12,
            },
            {
                "username": "dr_aur_gp",
                "first_name": "Genesis",
                "last_name": "Brady",
                "email": "g.brady@carelink.com",
                "specialty": "General Practice",
                "clinic_name": "Aurora Family Medicine",
                "clinic_address": "13123 E 16th Ave, Aurora, CO 80045",
                "consultation_fee": 140.00,
                "years_of_experience": 8,
            },
            # Raleigh, NC - More doctors
            {
                "username": "dr_ral_ortho",
                "first_name": "Aubrey",
                "last_name": "McMahon",
                "email": "a.mcmahon@carelink.com",
                "specialty": "Orthopedics",
                "clinic_name": "Raleigh Orthopedic",
                "clinic_address": "3000 New Bern Ave, Raleigh, NC 27610",
                "consultation_fee": 335.00,
                "years_of_experience": 16,
            },
            {
                "username": "dr_ral_ped",
                "first_name": "Brianna",
                "last_name": "Donovan",
                "email": "b.donovan@carelink.com",
                "specialty": "Pediatrics",
                "clinic_name": "Raleigh Children's Hospital",
                "clinic_address": "3100 Blue Ridge Rd, Raleigh, NC 27612",
                "consultation_fee": 176.00,
                "years_of_experience": 9,
            },
            # Omaha, NE - More doctors
            {
                "username": "dr_oma_derm",
                "first_name": "Skylar",
                "last_name": "Mccarty",
                "email": "s.mccarty@carelink.com",
                "specialty": "Dermatology",
                "clinic_name": "Omaha Dermatology",
                "clinic_address": "8200 Dodge St, Omaha, NE 68114",
                "consultation_fee": 260.00,
                "years_of_experience": 11,
            },
            {
                "username": "dr_oma_gp",
                "first_name": "Lucy",
                "last_name": "Cline",
                "email": "l.cline@carelink.com",
                "specialty": "General Practice",
                "clinic_name": "Omaha Family Medicine",
                "clinic_address": "8200 Dodge St, Omaha, NE 68114",
                "consultation_fee": 135.00,
                "years_of_experience": 7,
            },
            # Additional cities to reach 5x target
            # Indianapolis, IN
            {
                "username": "dr_ind_cardio",
                "first_name": "Maya",
                "last_name": "Valdez",
                "email": "m.valdez@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Indianapolis Heart Center",
                "clinic_address": "1801 N Senate Blvd, Indianapolis, IN 46202",
                "consultation_fee": 290.00,
                "years_of_experience": 14,
            },
            {
                "username": "dr_ind_ped",
                "first_name": "Aria",
                "last_name": "Maldonado",
                "email": "a.maldonado@carelink.com",
                "specialty": "Pediatrics",
                "clinic_name": "Indianapolis Children's Hospital",
                "clinic_address": "705 Riley Hospital Dr, Indianapolis, IN 46202",
                "consultation_fee": 175.00,
                "years_of_experience": 9,
            },
            # Colorado Springs, CO
            {
                "username": "dr_cs_cardio",
                "first_name": "Luna",
                "last_name": "Brewer",
                "email": "l.brewer@carelink.com",
                "specialty": "Cardiology",
                "clinic_name": "Colorado Springs Heart Center",
                "clinic_address": "1400 E Boulder St, Colorado Springs, CO 80909",
                "consultation_fee": 285.00,
                "years_of_experience": 13,
            },
            {
                "username": "dr_cs_ortho",
                "first_name": "Zoe",
                "last_name": "Warren",
                "email": "z.warren@carelink.com",
                "specialty": "Orthopedics",
                "clinic_name": "Colorado Springs Orthopedic",
                "clinic_address": "1400 E Boulder St, Colorado Springs, CO 80909",
                "consultation_fee": 340.00,
                "years_of_experience": 16,
            },
            # Raleigh, NC - More
            {
                "username": "dr_ral_neuro",
                "first_name": "Chloe",
                "last_name": "Mendoza",
                "email": "c.mendoza@carelink.com",
                "specialty": "Neurology",
                "clinic_name": "Raleigh Neurological Center",
                "clinic_address": "3000 New Bern Ave, Raleigh, NC 27610",
                "consultation_fee": 330.00,
                "years_of_experience": 17,
            },
            # Virginia Beach, VA - More
            {
                "username": "dr_vb_neuro",
                "first_name": "Isabella",
                "last_name": "Vargas",
                "email": "i.vargas@carelink.com",
                "specialty": "Neurology",
                "clinic_name": "Virginia Beach Neurological",
                "clinic_address": "600 Gresham Dr, Norfolk, VA 23507",
                "consultation_fee": 325.00,
                "years_of_experience": 16,
            },
            # Oakland, CA - More
            {
                "username": "dr_oak_neuro",
                "first_name": "Sophia",
                "last_name": "Guerrero",
                "email": "s.guerrero@carelink.com",
                "specialty": "Neurology",
                "clinic_name": "Oakland Neurological Center",
                "clinic_address": "747 52nd St, Oakland, CA 94609",
                "consultation_fee": 335.00,
                "years_of_experience": 18,
            },
            # Minneapolis, MN - More
            {
                "username": "dr_min_neuro",
                "first_name": "Emma",
                "last_name": "Hudson",
                "email": "e.hudson@carelink.com",
                "specialty": "Neurology",
                "clinic_name": "Minneapolis Neurological",
                "clinic_address": "800 E 28th St, Minneapolis, MN 55407",
                "consultation_fee": 320.00,
                "years_of_experience": 15,
            },
            # Tulsa, OK - More
            {
                "username": "dr_tul_neuro",
                "first_name": "Olivia",
                "last_name": "Spencer",
                "email": "o.spencer@carelink.com",
                "specialty": "Neurology",
                "clinic_name": "Tulsa Neurological Center",
                "clinic_address": "6161 S Yale Ave, Tulsa, OK 74136",
                "consultation_fee": 315.00,
                "years_of_experience": 14,
            },
            # Arlington, TX - More
            {
                "username": "dr_arl_neuro",
                "first_name": "Amelia",
                "last_name": "Vincent",
                "email": "a.vincent@carelink.com",
                "specialty": "Neurology",
                "clinic_name": "Arlington Neurological",
                "clinic_address": "800 W Randol Mill Rd, Arlington, TX 76012",
                "consultation_fee": 310.00,
                "years_of_experience": 13,
            },
            # Tampa, FL - More
            {
                "username": "dr_tam_neuro",
                "first_name": "Harper",
                "last_name": "Tucker",
                "email": "h.tucker@carelink.com",
                "specialty": "Neurology",
                "clinic_name": "Tampa Neurological Center",
                "clinic_address": "1 Tampa General Cir, Tampa, FL 33606",
                "consultation_fee": 318.00,
                "years_of_experience": 15,
            },
            # New Orleans, LA - More
            {
                "username": "dr_no_neuro",
                "first_name": "Evelyn",
                "last_name": "Porter",
                "email": "e.porter@carelink.com",
                "specialty": "Neurology",
                "clinic_name": "New Orleans Neurological",
                "clinic_address": "1514 Jefferson Hwy, New Orleans, LA 70121",
                "consultation_fee": 312.00,
                "years_of_experience": 14,
            },
            # Cleveland, OH - More
            {
                "username": "dr_cle_neuro",
                "first_name": "Abigail",
                "last_name": "Hunter",
                "email": "a.hunter@carelink.com",
                "specialty": "Neurology",
                "clinic_name": "Cleveland Neurological Center",
                "clinic_address": "9500 Euclid Ave, Cleveland, OH 44195",
                "consultation_fee": 328.00,
                "years_of_experience": 16,
            },
            # Wichita, KS - More
            {
                "username": "dr_wic_neuro",
                "first_name": "Emily",
                "last_name": "Hicks",
                "email": "e.hicks@carelink.com",
                "specialty": "Neurology",
                "clinic_name": "Wichita Neurological",
                "clinic_address": "929 N Waco St, Wichita, KS 67203",
                "consultation_fee": 305.00,
                "years_of_experience": 13,
            },
            # Bakersfield, CA - More
            {
                "username": "dr_bak_neuro",
                "first_name": "Elizabeth",
                "last_name": "Crawford",
                "email": "e.crawford@carelink.com",
                "specialty": "Neurology",
                "clinic_name": "Bakersfield Neurological",
                "clinic_address": "1830 Flower St, Bakersfield, CA 93305",
                "consultation_fee": 298.00,
                "years_of_experience": 12,
            },
            # Aurora, CO - More
            {
                "username": "dr_aur_neuro",
                "first_name": "Mila",
                "last_name": "Henry",
                "email": "m.henry@carelink.com",
                "specialty": "Neurology",
                "clinic_name": "Aurora Neurological Center",
                "clinic_address": "12605 E 16th Ave, Aurora, CO 80045",
                "consultation_fee": 308.00,
                "years_of_experience": 14,
            },
            # Raleigh, NC - More
            {
                "username": "dr_ral_im",
                "first_name": "Avery",
                "last_name": "Boyd",
                "email": "a.boyd@carelink.com",
                "specialty": "Internal Medicine",
                "clinic_name": "Raleigh Internal Medicine",
                "clinic_address": "3000 New Bern Ave, Raleigh, NC 27610",
                "consultation_fee": 205.00,
                "years_of_experience": 11,
            },
            # Omaha, NE - More
            {
                "username": "dr_oma_neuro",
                "first_name": "Sofia",
                "last_name": "Mason",
                "email": "s.mason@carelink.com",
                "specialty": "Neurology",
                "clinic_name": "Omaha Neurological Center",
                "clinic_address": "8200 Dodge St, Omaha, NE 68114",
                "consultation_fee": 300.00,
                "years_of_experience": 13,
            },
            # Miami, FL - More
            {
                "username": "dr_mia_neuro",
                "first_name": "Camila",
                "last_name": "Morales",
                "email": "c.morales@carelink.com",
                "specialty": "Neurology",
                "clinic_name": "Miami Neurological Center",
                "clinic_address": "1611 NW 12th Ave, Miami, FL 33136",
                "consultation_fee": 315.00,
                "years_of_experience": 14,
            },
            # Long Beach, CA - More
            {
                "username": "dr_lb_neuro",
                "first_name": "Aria",
                "last_name": "Ferguson",
                "email": "a.ferguson.lb@carelink.com",
                "specialty": "Neurology",
                "clinic_name": "Long Beach Neurological",
                "clinic_address": "2801 Atlantic Ave, Long Beach, CA 90806",
                "consultation_fee": 310.00,
                "years_of_experience": 13,
            },
            # Virginia Beach, VA - More
            {
                "username": "dr_vb_im",
                "first_name": "Scarlett",
                "last_name": "Rose",
                "email": "s.rose@carelink.com",
                "specialty": "Internal Medicine",
                "clinic_name": "Virginia Beach Internal Medicine",
                "clinic_address": "600 Gresham Dr, Norfolk, VA 23507",
                "consultation_fee": 195.00,
                "years_of_experience": 10,
            },
            # Oakland, CA - More
            {
                "username": "dr_oak_obgyn",
                "first_name": "Victoria",
                "last_name": "Stone",
                "email": "v.stone@carelink.com",
                "specialty": "Obstetrics & Gynecology",
                "clinic_name": "Oakland Women's Health",
                "clinic_address": "747 52nd St, Oakland, CA 94609",
                "consultation_fee": 245.00,
                "years_of_experience": 12,
            },
            # Minneapolis, MN - More
            {
                "username": "dr_min_obgyn",
                "first_name": "Madison",
                "last_name": "Hawkins",
                "email": "m.hawkins@carelink.com",
                "specialty": "Obstetrics & Gynecology",
                "clinic_name": "Minneapolis Women's Health",
                "clinic_address": "800 E 28th St, Minneapolis, MN 55407",
                "consultation_fee": 242.00,
                "years_of_experience": 11,
            },
            # Tulsa, OK - More
            {
                "username": "dr_tul_im",
                "first_name": "Luna",
                "last_name": "Grant",
                "email": "l.grant@carelink.com",
                "specialty": "Internal Medicine",
                "clinic_name": "Tulsa Internal Medicine",
                "clinic_address": "6161 S Yale Ave, Tulsa, OK 74136",
                "consultation_fee": 188.00,
                "years_of_experience": 9,
            },
            # Arlington, TX - More
            {
                "username": "dr_arl_im",
                "first_name": "Grace",
                "last_name": "Nichols",
                "email": "g.nichols@carelink.com",
                "specialty": "Internal Medicine",
                "clinic_name": "Arlington Internal Medicine",
                "clinic_address": "800 W Randol Mill Rd, Arlington, TX 76012",
                "consultation_fee": 185.00,
                "years_of_experience": 8,
            },
            # Tampa, FL - More
            {
                "username": "dr_tam_im",
                "first_name": "Chloe",
                "last_name": "Robertson",
                "email": "c.robertson@carelink.com",
                "specialty": "Internal Medicine",
                "clinic_name": "Tampa Internal Medicine",
                "clinic_address": "1 Tampa General Cir, Tampa, FL 33606",
                "consultation_fee": 192.00,
                "years_of_experience": 10,
            },
            # New Orleans, LA - More
            {
                "username": "dr_no_im",
                "first_name": "Penelope",
                "last_name": "Knight",
                "email": "p.knight@carelink.com",
                "specialty": "Internal Medicine",
                "clinic_name": "New Orleans Internal Medicine",
                "clinic_address": "1514 Jefferson Hwy, New Orleans, LA 70121",
                "consultation_fee": 190.00,
                "years_of_experience": 9,
            },
            # Cleveland, OH - More
            {
                "username": "dr_cle_im",
                "first_name": "Riley",
                "last_name": "Strickland",
                "email": "r.strickland@carelink.com",
                "specialty": "Internal Medicine",
                "clinic_name": "Cleveland Internal Medicine",
                "clinic_address": "9500 Euclid Ave, Cleveland, OH 44195",
                "consultation_fee": 198.00,
                "years_of_experience": 11,
            },
            # Wichita, KS - More
            {
                "username": "dr_wic_im",
                "first_name": "Layla",
                "last_name": "Dixon",
                "email": "l.dixon@carelink.com",
                "specialty": "Internal Medicine",
                "clinic_name": "Wichita Internal Medicine",
                "clinic_address": "929 N Waco St, Wichita, KS 67203",
                "consultation_fee": 183.00,
                "years_of_experience": 8,
            },
            # Bakersfield, CA - More
            {
                "username": "dr_bak_im",
                "first_name": "Nora",
                "last_name": "Hoffman",
                "email": "n.hoffman@carelink.com",
                "specialty": "Internal Medicine",
                "clinic_name": "Bakersfield Internal Medicine",
                "clinic_address": "1830 Flower St, Bakersfield, CA 93305",
                "consultation_fee": 180.00,
                "years_of_experience": 7,
            },
            # Aurora, CO - More
            {
                "username": "dr_aur_im",
                "first_name": "Zoey",
                "last_name": "Cunningham",
                "email": "z.cunningham@carelink.com",
                "specialty": "Internal Medicine",
                "clinic_name": "Aurora Internal Medicine",
                "clinic_address": "12605 E 16th Ave, Aurora, CO 80045",
                "consultation_fee": 187.00,
                "years_of_experience": 8,
            },
            # Raleigh, NC - More
            {
                "username": "dr_ral_obgyn",
                "first_name": "Lillian",
                "last_name": "Schneider",
                "email": "l.schneider@carelink.com",
                "specialty": "Obstetrics & Gynecology",
                "clinic_name": "Raleigh Women's Health",
                "clinic_address": "3000 New Bern Ave, Raleigh, NC 27610",
                "consultation_fee": 238.00,
                "years_of_experience": 11,
            },
            # Omaha, NE - More
            {
                "username": "dr_oma_obgyn",
                "first_name": "Addison",
                "last_name": "Schultz",
                "email": "a.schultz@carelink.com",
                "specialty": "Obstetrics & Gynecology",
                "clinic_name": "Omaha Women's Health",
                "clinic_address": "8200 Dodge St, Omaha, NE 68114",
                "consultation_fee": 235.00,
                "years_of_experience": 10,
            },
        ]

        created_count = 0
        geocoded_count = 0
        count = min(options["count"], len(doctors_data))

        for i, data in enumerate(doctors_data[:count]):
            # Create or get user
            user, user_created = User.objects.get_or_create(
                username=data["username"],
                defaults={
                    "first_name": data["first_name"],
                    "last_name": data["last_name"],
                    "email": data["email"],
                },
            )

            if user_created:
                user.set_password("password123")
                user.save()
                self.stdout.write(f"Created user: {data['username']}")

            # Create or update doctor profile
            doctor_profile, profile_created = DoctorProfile.objects.get_or_create(
                user=user,
                defaults={
                    "specialty": data["specialty"],
                    "bio": (
                        f'Experienced {data["specialty"]} physician with '
                        f'{data["years_of_experience"]} years of practice.'
                    ),
                    "clinic_name": data["clinic_name"],
                    "clinic_address": data["clinic_address"],
                    "consultation_fee": data["consultation_fee"],
                    "years_of_experience": data["years_of_experience"],
                },
            )

            # Update if it already existed
            if not profile_created:
                doctor_profile.specialty = data["specialty"]
                doctor_profile.clinic_name = data["clinic_name"]
                doctor_profile.clinic_address = data["clinic_address"]
                doctor_profile.consultation_fee = data["consultation_fee"]
                doctor_profile.years_of_experience = data["years_of_experience"]
                if not doctor_profile.bio:
                    doctor_profile.bio = (
                        f'Experienced {data["specialty"]} physician with '
                        f'{data["years_of_experience"]} years of practice.'
                    )
                doctor_profile.save()

            # Geocode if coordinates are missing
            if not doctor_profile.clinic_latitude or not doctor_profile.clinic_longitude:
                time.sleep(1.5)  # Rate limiting for geocoding API
                lat, lon = geocode_location(doctor_profile.clinic_address)
                if lat is not None and lon is not None:
                    doctor_profile.clinic_latitude = lat
                    doctor_profile.clinic_longitude = lon
                    doctor_profile.save()
                    geocoded_count += 1
                    self.stdout.write(
                        self.style.SUCCESS(
                            f"  ✓ Geocoded {doctor_profile.clinic_name} "
                            f"({data['clinic_address'].split(',')[0]}): "
                            f"({lat}, {lon})"
                        )
                    )
                else:
                    self.stdout.write(
                        self.style.WARNING(f"  ✗ Failed to geocode: {doctor_profile.clinic_name}")
                    )

            if profile_created:
                created_count += 1
                self.stdout.write(
                    f"Created doctor: Dr. {data['first_name']} {data['last_name']} "
                    f"- {data['specialty']} in {data['clinic_address'].split(',')[-2].strip()}"
                )

                # Create default availability (Mon-Fri 9-5)
                for day in range(5):  # Monday to Friday
                    DoctorAvailability.objects.create(
                        doctor=doctor_profile,
                        day_of_week=day,
                        start_time="09:00",
                        end_time="17:00",
                        is_available=True,
                    )

        self.stdout.write(
            self.style.SUCCESS(
                f"\n✓ Created {created_count} new doctor profiles\n"
                f"✓ Geocoded {geocoded_count} clinic addresses\n"
                f"✓ Doctors now available across {count} US cities"
            )
        )
