# Generated by Django 5.1.1 on 2025-11-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="appointment_type",
            field=models.CharField(
                choices=[("in_person", "In Person"), ("virtual", "Virtual Visit")],
                default="in_person",
                help_text="Type of appointment: in-person or virtual",
                max_length=20,
            ),
        ),
    ]
