# Generated by Django 5.1.1 on 2025-12-06 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        help_text="Medical specialty (e.g., General Practice, Cardiology)",
                        max_length=100,
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, help_text="Professional biography and background"),
                ),
                (
                    "clinic_name",
                    models.CharField(help_text="Name of the clinic or hospital", max_length=200),
                ),
                ("clinic_address", models.TextField(help_text="Physical address of the clinic")),
                (
                    "consultation_fee",
                    models.DecimalField(
                        decimal_places=2, help_text="Standard consultation fee", max_digits=10
                    ),
                ),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(default=0, help_text="Years of medical practice"),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        help_text="Doctor's profile picture",
                        null=True,
                        upload_to="doctors/profiles/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DoctorAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        help_text="Day of the week",
                    ),
                ),
                ("start_time", models.TimeField(help_text="Shift start time")),
                ("end_time", models.TimeField(help_text="Shift end time")),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, help_text="Whether the doctor is available on this day"
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="doctors.doctorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor Availability",
                "verbose_name_plural": "Doctor Availabilities",
                "ordering": ["day_of_week", "start_time"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("doctor", "day_of_week"), name="unique_doctor_day_availability"
                    )
                ],
            },
        ),
    ]
