# Generated by Django 5.1.1 on 2025-12-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctoravailability",
            name="end_time",
            field=models.TimeField(blank=True, help_text="Shift end time", null=True),
        ),
        migrations.AlterField(
            model_name="doctoravailability",
            name="start_time",
            field=models.TimeField(blank=True, help_text="Shift start time", null=True),
        ),
    ]
