# Generated by Django 5.0 on 2025-12-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_alter_doctoravailability_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="clinic_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Clinic latitude coordinate",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="clinic_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Clinic longitude coordinate",
                max_digits=9,
                null=True,
            ),
        ),
    ]
